sudo: required 
dist: xenial 
language: generic 
compiler:
  - gcc
notifications:
  email:
    on_success: always
    on_failure: always
env:
  global:
    - ROS_DISTRO=kinetic
    - UPSTREAM_WORKSPACE=file
    - ROSINSTALL_FILENAME=IC2.rosinstall
    - NOT_TEST_INSTALL=true
  matrix:
    - ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script: 
  - travis_wait 30 source .ci_config/travis.sh